export const moodObj = [
  [
    {
      id: "1",
      text: "설레요",
      color: "#fd79a8",
      selected: false,
      keyword: "love",
    },
    {
      id: "2",
      text: "신나요",
      color: "#FFC312",
      selected: false,
      keyword: "excited",
    },
    {
      id: "3",
      text: "편안해요",
      color: "#55efc4",
      selected: false,
      keyword: "chill",
    },
  ],
  [
    {
      id: "4",
      text: "답답해요",
      color: "#F79F1F",
      selected: false,
      keyword: "frustrated",
    },
    {
      id: "5",
      text: "지루해요",
      color: "#133936",
      selected: false,
      keyword: "bored",
    },
  ],
  [
    {
      id: "6",
      text: "그리워요",
      color: "#686de0",
      selected: false,
      keyword: "lonely",
    },
    {
      id: "7",
      text: "속상해요",
      color: "#9b59b6",
      selected: false,
      keyword: "sad",
    },
    {
      id: "8",
      text: "화나요",
      color: "#e74c3c",
      selected: false,
      keyword: "angry",
    },
  ],
  [
    {
      id: "9",
      text: "허무해요",
      color: "#4b6584",
      selected: false,
      keyword: "empty",
    },
    {
      id: "10",
      text: "야릇해요",
      color: "#B53471",
      selected: false,
      keyword: "chic",
    },
  ],
];

export const playlists = {
  "love-excited": "2bq1xvQnYRZBP2OoOVsFHb",
  "love-chill": "6MWWmGh6pfK9QYZBGCamRC",
  "love-frustrated": "6iPNVcWkJKOhyxPKt8Zq4Z",
  "love-bored": "5C4iHRVQbvopBsa1PUkBQw",
  "love-lonely": "6MzSr4VR5ci62CpgeFd91l",
  "love-sad": "4vVVXb8nytZmq6qGBt10ni",
  "love-angry": "6DOrWmeJm9HtvWknZYh1ls",
  "love-empty": "6IoSijtnf3CGxQzAznpCR5",
  "love-chic": "0glH1uXB8HQEvwIDyyEgeW",
  "excited-chill": "0lqthpVuoZBmnjOa8sU0Kw",
  "excited-frustrated": "503Pyl2vZDGDVTubNQsfih",
  "excited-bored": "3nbZLJrm4JPFcHn4QNaqkE",
  "excited-lonely": "0Nz9245adTUEPpDs71RZRj",
  "excited-sad": "00KuNH8nfsCV9yg0Y4DHXo",
  "excited-angry": "1D026nYiC2JWGIlkbwmlsO",
  "excited-empty": "73zXLxWNIc2W2i5iTj5bH4",
  "excited-chic": "3j2IHfiyEiFm0LtGMIvncc",
  "chill-frustrated": "1XONboV2rIWBlZm0VbKMXb",
  "chill-bored": "7pTUApmbjMVXdEX3JCgr0m",
  "chill-lonely": "3eaqg3t82iy5YGepH3XJOF",
  "chill-sad": "40viuxqFFOGQzSxyLlsVeT",
  "chill-angry": "0pj1rr2HpsF8jHbDHOYznh",
  "chill-empty": "0hrXC18sIabyQMyq3Up5i9",
  "chill-chic": "1L6W7MohnKL2dkre4IVw6v",
  "frustrated-bored": "1asvGDpJWoP2V9XTbjmT3v",
  "frustrated-lonely": "7McdTWFJcbdZHx4Mi1xOvE",
  "frustrated-sad": "7kERwxrqyVl1groIrJAiGK",
  "frustrated-angry": "56AMay6i7ktf7POVfcTQdl",
  "frustrated-empty": "3AS3UPOUL1tbeNHLTzBru7",
  "frustrated-chic": "75Rn1hWjDsI6cW0UxQEubP",
  "bored-lonely": "2knWQSUCcp0jbUSYfdmJ0Q",
  "bored-sad": "7gbx1lbYd1lmHG1S933Lz7",
  "bored-angry": "56lGKo8XIKOPY4zs0UlaCy",
  "bored-empty": "1fZknp59oIQJudBhbO8Tem",
  "bored-chic": "63bptaQSePOevQFn3Ms9o1",
  "lonely-sad": "6NSibKqLhA8ynL0mUdqW9T",
  "lonely-angry": "0YgiBw5bSSGfCHJdEWG4bM",
  "lonely-empty": "2FP4uTYLX8lXBvMXCM0r6q",
  "lonely-chic": "2J3prWn5DJClvE1JdpPtH5",
  "sad-angry": "2pNfv5DvBXRFiZkO80UELj",
  "sad-empty": "0d8ajZSMnlcyZ5hq4C0NXC",
  "sad-chic": "6FqfRgpGEoK4flOyguQSbg",
  "angry-empty": "6DKEkYG21QHTvioVw6A0xl",
  "angry-chic": "6cJ2Y1Obp05iT1GOAPGmtc",
  "empty-chic": "4DSJpKOtNCUYtYSxOJsfD0",
};
